# Generated by Django 4.2.4 on 2023-09-07 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotedCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='TrackedQuotedCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Пороговое Значение')),
                ('quoted_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_by_users', to='quotes.quotedcurrency', verbose_name='Отслеживаемая Валюта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_quoted_currencies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='QuotedCurrencyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbr_id', models.CharField(max_length=10, verbose_name='ID ЦБ РФ')),
                ('cbr_num_code', models.CharField(max_length=3, verbose_name='Числовой Код ЦБ РФ')),
                ('cbr_nominal', models.IntegerField(verbose_name='Номинал ЦБ РФ')),
                ('cbr_name', models.CharField(max_length=255, verbose_name='Название ЦБ РФ')),
                ('cbr_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Значение ЦБ РФ')),
                ('cbr_previous_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Предыдущее Значение ЦБ РФ')),
                ('cbr_date', models.DateTimeField(verbose_name='Дата')),
                ('cbr_previous_date', models.DateTimeField(verbose_name='Предыдущая Дата')),
                ('quoted_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='quotes.quotedcurrency', verbose_name='Валюта')),
            ],
        ),
    ]
